# Generated by Django 2.2.1 on 2019-05-21 03:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('activity_type', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('plaform_type', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('age_restriction', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CommuTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tweet_id', models.CharField(max_length=20)),
                ('promote_request_tweet_id', models.CharField(max_length=20, unique=True)),
                ('previous_retweet_id', models.CharField(max_length=20, unique=True)),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('user_screen_name', models.CharField(max_length=30)),
                ('profile_image_url_https', models.CharField(max_length=100)),
                ('media', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('commu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commu.Commu')),
                ('commu_tweet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commu.CommuTweet')),
                ('tags', models.ManyToManyField(related_name='commu_tag', to='commu.Tag')),
            ],
        ),
    ]
