# Generated by Django 2.2.1 on 2019-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommuTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('tweet_id', models.CharField(max_length=20)),
                ('promote_request_tweet_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('user_screen_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
